package main

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strings"

	"key-box/internal/auth"
	"key-box/internal/config"
	"key-box/internal/db"
	"key-box/internal/vault"
)

var (
	autoGeneratedSalt string
)

func main() {
	// 1. Check Salt (优先从配置文件读取，其次从环境变量读取)
	salt, err := config.GetSalt()
	if err != nil {
		fmt.Printf("Error reading salt: %v\n", err)
		os.Exit(1)
	}
	if salt == "" {
		// Generate random salt
		b := make([]byte, 16)
		if _, err := rand.Read(b); err != nil {
			fmt.Printf("Error generating random salt: %v\n", err)
			os.Exit(1)
		}
		autoGeneratedSalt = hex.EncodeToString(b)
		// 保存到配置文件
		if err := config.SaveSalt(autoGeneratedSalt); err != nil {
			fmt.Printf("Warning: failed to save salt to config file: %v\n", err)
		}
	}

	// 2. Init DB
	database, err := db.InitDB()
	if err != nil {
		fmt.Printf("Error initializing database: %v\n", err)
		os.Exit(1)
	}

	authService := auth.NewService(database)
	vaultManager := vault.NewManager(database)
	scanner := bufio.NewScanner(os.Stdin)

	for {
		fmt.Println("\n=== 本地密码管理器 (Local Password Manager) ===")
		fmt.Println("1. 注册 (Register)")
		fmt.Println("2. 登录 (Login)")
		fmt.Println("3. 重置密码 (Reset Password)")
		fmt.Println("4. 退出 (Exit)")
		fmt.Print("请选择 (1-4): ")

		if !scanner.Scan() {
			break
		}
		choice := strings.TrimSpace(scanner.Text())

		switch choice {
		case "1":
			handleRegister(scanner, authService)
		case "2":
			handleLogin(scanner, authService, vaultManager)
		case "3":
			handleReset(scanner, authService)
		case "4":
			fmt.Println("Bye!")
			return
		default:
			fmt.Println("无效选项")
		}
	}
}

func handleRegister(scanner *bufio.Scanner, s *auth.Service) {
	if autoGeneratedSalt != "" {
		fmt.Println("\n[Warning] 未检测到 Salt 配置。")
		fmt.Printf("已自动生成 Salt: %s\n", autoGeneratedSalt)
		fmt.Println("Salt 已保存到配置文件 ~/.key-box.config")
		fmt.Println("请确保该配置文件安全存储，否则将无法解密本次注册的数据。")
		fmt.Println()
		fmt.Println("也可以通过环境变量配置 (优先级低于配置文件):")
		fmt.Printf("Mac/Linux: export SEC_APP_SALT=\"%s\"\n", autoGeneratedSalt)
		fmt.Printf("Windows:   $env:SEC_APP_SALT=\"%s\"\n", autoGeneratedSalt)
		fmt.Print("按回车键继续...")
		scanner.Scan()
	}

	fmt.Println("\n--- 注册 ---")
	fmt.Print("用户名: ")
	scanner.Scan()
	username := strings.TrimSpace(scanner.Text())

	fmt.Print("密保问题 1: ")
	scanner.Scan()
	q1 := strings.TrimSpace(scanner.Text())
	fmt.Print("答案 1: ")
	scanner.Scan()
	a1 := strings.TrimSpace(scanner.Text())

	fmt.Print("密保问题 2: ")
	scanner.Scan()
	q2 := strings.TrimSpace(scanner.Text())
	fmt.Print("答案 2: ")
	scanner.Scan()
	a2 := strings.TrimSpace(scanner.Text())

	fmt.Print("密保问题 3: ")
	scanner.Scan()
	q3 := strings.TrimSpace(scanner.Text())
	fmt.Print("答案 3: ")
	scanner.Scan()
	a3 := strings.TrimSpace(scanner.Text())

	res, err := s.Register(username, q1, q2, q3, a1, a2, a3)
	if err != nil {
		fmt.Printf("注册失败: %v\n", err)
		return
	}

	fmt.Println("注册成功!")
	fmt.Println("请务必保存您的最高权限恢复凭证 (Key B) 到您的 OTP Authenticator App (如 Google Authenticator):")
	fmt.Println("----------------------------------------------------------------")
	fmt.Printf("Secret Key (Base32): %s\n", res.SecretKeyBBase32)
	fmt.Println("----------------------------------------------------------------")
	fmt.Println("您也可以手动输入上述 Key 到 App 中。")
}

func handleLogin(scanner *bufio.Scanner, s *auth.Service, v *vault.Manager) {
	if autoGeneratedSalt != "" {
		fmt.Println("\n[Warning] 未检测到 Salt 配置。")
		fmt.Printf("已自动生成 Salt: %s\n", autoGeneratedSalt)
		fmt.Println("如果之前的数据是使用其他 Salt 加密的，登录将会失败。")
		fmt.Println("请确保配置文件 ~/.key-box.config 中的 Salt 与注册时一致。")
		fmt.Println("或通过环境变量覆盖:")
		fmt.Printf("Mac/Linux: export SEC_APP_SALT=\"...\"\n")
		fmt.Printf("Windows:   $env:SEC_APP_SALT=\"...\"\n")
		fmt.Print("按回车键继续...")
		scanner.Scan()
	}

	fmt.Println("\n--- 登录 ---")
	fmt.Print("用户名: ")
	scanner.Scan()
	username := strings.TrimSpace(scanner.Text())

	fmt.Print("请输入 6 位 OTP 验证码: ")
	scanner.Scan()
	otp := strings.TrimSpace(scanner.Text())

	keyC, err := s.Login(username, otp)
	if err != nil {
		fmt.Printf("登录失败: %v\n", err)
		return
	}

	fmt.Println("登录成功! 进入密码库...")
	handleVault(scanner, v, username, keyC)
}

func handleVault(scanner *bufio.Scanner, v *vault.Manager, username string, keyC []byte) {
	for {
		fmt.Printf("\n=== 密码库 (%s) ===\n", username)
		fmt.Println("1. 查看所有密码 (List)")
		fmt.Println("2. 添加密码 (Add)")
		fmt.Println("3. 退出登录 (Logout)")
		fmt.Print("请选择: ")

		if !scanner.Scan() {
			break
		}
		choice := strings.TrimSpace(scanner.Text())

		switch choice {
		case "1":
			items, err := v.ListItems(username, keyC)
			if err != nil {
				fmt.Printf("读取失败: %v\n", err)
			} else {
				fmt.Println("\n[存储的密码]")
				for _, item := range items {
					fmt.Printf("ID: %d | Site: %s | User: %s | Pass: %s\n", item.ID, item.Site, item.Username, item.Password)
				}
			}
		case "2":
			fmt.Print("网站/应用名: ")
			scanner.Scan()
			site := strings.TrimSpace(scanner.Text())
			fmt.Print("账号: ")
			scanner.Scan()
			u := strings.TrimSpace(scanner.Text())
			fmt.Print("密码: ")
			scanner.Scan()
			p := strings.TrimSpace(scanner.Text())

			if err := v.AddItem(username, keyC, site, u, p); err != nil {
				fmt.Printf("添加失败: %v\n", err)
			} else {
				fmt.Println("添加成功!")
			}
		case "3":
			return
		default:
			fmt.Println("无效选项")
		}
	}
}

func handleReset(scanner *bufio.Scanner, s *auth.Service) {
	fmt.Println("\n--- 密码重置 ---")
	fmt.Print("用户名: ")
	scanner.Scan()
	username := strings.TrimSpace(scanner.Text())

	questions, err := s.GetSecurityQuestions(username)
	if err != nil {
		fmt.Printf("查询失败 (用户不存在?): %v\n", err)
		return
	}

	fmt.Printf("问题 1: %s\n", questions[0])
	fmt.Print("答案 1: ")
	scanner.Scan()
	a1 := strings.TrimSpace(scanner.Text())

	fmt.Printf("问题 2: %s\n", questions[1])
	fmt.Print("答案 2: ")
	scanner.Scan()
	a2 := strings.TrimSpace(scanner.Text())

	fmt.Printf("问题 3: %s\n", questions[2])
	fmt.Print("答案 3: ")
	scanner.Scan()
	a3 := strings.TrimSpace(scanner.Text())

	res, err := s.ResetPassword(username, a1, a2, a3)
	if err != nil {
		fmt.Printf("重置失败: %v\n", err)
		return
	}

	fmt.Println("重置成功!")
	fmt.Println("新的最高权限恢复凭证 (Key B):")
	fmt.Printf("Secret Key (Base32): %s\n", res.SecretKeyBBase32)
}
